import os
import sys
import io
import traceback
import json

import uvicorn

from fastapi import FastAPI

from langserve import add_routes

from langchain_core.tools import tool
from langchain_core.runnables import RunnableLambda
from langchain_google_genai import ChatGoogleGenerativeAI

from langgraph.graph import StateGraph, START, END

from pydantic import BaseModel, Field

from typing import TypedDict


# ============================================================
# 1. GET GEMINI API KEY FROM RENDER ENVIRONMENT
# ============================================================

GOOGLE_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GOOGLE_API_KEY:
    raise RuntimeError(
        "GEMINI_API_KEY environment variable is not set."
    )


# ============================================================
# 2. INITIALIZE GEMINI
# ============================================================

llm_flash = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite-preview",
    google_api_key=GOOGLE_API_KEY,
    temperature=0
)

llm = llm_flash


# ============================================================
# 3. STATE DEFINITION
# ============================================================

class CrewState(TypedDict, total=False):

    # User's coding task
    task: str

    # Code generated by Developer
    code: str

    # Test cases generated by Tester
    test_cases: str

    # Actual code execution result
    execution_output: str

    # Tester report
    report: str

    # Manager decision
    decision: str


# ============================================================
# 4. HELPER FUNCTION
# ============================================================

def extract_text(content) -> str:
    """
    Safely extract text from Gemini response content.
    """

    if content is None:
        return ""

    if isinstance(content, str):
        return content

    if isinstance(content, list):

        result = []

        for item in content:

            if isinstance(item, dict):

                if "text" in item:
                    result.append(
                        str(item["text"])
                    )

            else:

                result.append(
                    str(item)
                )

        return "".join(result)

    return str(content)


# ============================================================
# 5. PYTHON CODE EXECUTION TOOL
# ============================================================

@tool
def run_python_code(code: str) -> str:
    """
    Execute Python code and return stdout or error.
    """

    if not isinstance(code, str):
        code = str(code)

    # Remove Markdown code fences
    clean_code = (
        code
        .replace("```python", "")
        .replace("```Python", "")
        .replace("```", "")
        .strip()
    )

    old_stdout = sys.stdout
    new_stdout = io.StringIO()

    sys.stdout = new_stdout

    try:

        local_scope = {}

        exec(
            clean_code,
            {},
            local_scope
        )

        result = new_stdout.getvalue()

    except Exception:

        result = (
            "Execution Error:\n"
            + traceback.format_exc()
        )

    finally:

        sys.stdout = old_stdout

    if result.strip():

        return result.strip()

    return "Success (no terminal output)"


# ============================================================
# 6. TEST CASE GENERATION TOOL
# ============================================================

@tool
def generate_test_cases(
    task_description: str
) -> str:
    """
    Generate QA test scenarios for a coding task.
    """

    prompt = f"""
You are a Senior QA Engineer.

Generate 3 to 5 specific test scenarios
for the following Python coding task:

{task_description}

Requirements:

1. Include normal cases.
2. Include edge cases.
3. Include invalid input cases when appropriate.
4. Explain what each test checks.
5. Return ONLY a numbered list.
"""

    response = llm.invoke(prompt)

    return extract_text(
        response.content
    )


# ============================================================
# 7. DEVELOPER NODE
# ============================================================

def developer_node(
    state: CrewState
):

    print("\n")
    print("=" * 60)
    print("DEVELOPER NODE")
    print("=" * 60)

    task = state.get("task")

    if not task:

        raise ValueError(
            "Developer did not receive a task."
        )

    print(
        "\nTask received by Developer:"
    )

    print(task)

    # --------------------------------------------------------
    # Developer prompt
    # --------------------------------------------------------

    prompt = f"""
You are a Senior Python Developer.

Solve the following coding task:

{task}

Requirements:

- Write clean Python code.
- Make it executable.
- Handle reasonable edge cases.
- Return ONLY Python source code.
- Do NOT return explanations.
- Do NOT return Markdown.
- Do NOT use ```python.
"""

    print(
        "\nDeveloper calling Gemini..."
    )

    response = llm.invoke(prompt)

    code = extract_text(
        response.content
    )

    # --------------------------------------------------------
    # Clean response
    # --------------------------------------------------------

    code = (
        code
        .replace("```python", "")
        .replace("```Python", "")
        .replace("```", "")
        .strip()
    )

    if not code:

        raise ValueError(
            "Developer generated empty code."
        )

    print(
        "\nDeveloper generated code:"
    )

    print("-" * 60)

    print(code)

    print("-" * 60)

    # --------------------------------------------------------
    # THIS IS THE STATE UPDATE
    # --------------------------------------------------------

    return {
        "code": code
    }


# ============================================================
# 8. TESTER NODE
# ============================================================

def tester_node(
    state: CrewState
):

    print("\n")
    print("=" * 60)
    print("TESTER NODE")
    print("=" * 60)

    # --------------------------------------------------------
    # Read state from Developer
    # --------------------------------------------------------

    task = state.get("task")

    code = state.get("code")

    print(
        "\nTester received code:",
        bool(code)
    )

    if not task:

        raise ValueError(
            "Tester did not receive task."
        )

    if not code:

        raise ValueError(
            "Tester did not receive Developer code."
        )

    # --------------------------------------------------------
    # Generate test cases
    # --------------------------------------------------------

    print(
        "\nGenerating test cases..."
    )

    test_cases = generate_test_cases.invoke(
        task
    )

    test_cases = extract_text(
        test_cases
    )

    # --------------------------------------------------------
    # Execute Developer code
    # --------------------------------------------------------

    print(
        "\nExecuting Developer code..."
    )

    execution_output = run_python_code.invoke(
        {
            "code": code
        }
    )

    # --------------------------------------------------------
    # Create report
    # --------------------------------------------------------

    report = f"""
### EXECUTION OUTPUT

{execution_output}


### TEST SCENARIOS EVALUATED

{test_cases}
"""

    print(
        "\nTester generated report:"
    )

    print("-" * 60)

    print(report)

    print("-" * 60)

    # --------------------------------------------------------
    # STATE UPDATE
    # --------------------------------------------------------

    return {
        "test_cases": test_cases,
        "execution_output": execution_output,
        "report": report
    }


# ============================================================
# 9. MANAGER NODE
# ============================================================

def manager_node(
    state: CrewState
):

    print("\n")
    print("=" * 60)
    print("MANAGER NODE")
    print("=" * 60)

    # --------------------------------------------------------
    # Read Tester state
    # --------------------------------------------------------

    task = state.get("task")

    code = state.get("code")

    test_cases = state.get(
        "test_cases"
    )

    execution_output = state.get(
        "execution_output"
    )

    report = state.get(
        "report"
    )

    if not report:

        raise ValueError(
            "Manager did not receive Tester report."
        )

    print(
        "\nManager received Tester report."
    )

    print("-" * 60)

    print(report)

    print("-" * 60)

    # --------------------------------------------------------
    # Manager prompt
    # --------------------------------------------------------

    manager_prompt = f"""
You are a Senior Engineering Manager.

Review this coding task:

{task}


DEVELOPER CODE:

{code}


TEST CASES:

{test_cases}


EXECUTION OUTPUT:

{execution_output}


TESTER REPORT:

{report}


Decide whether the implementation is acceptable.

Return ONLY one of these:

APPROVED

or

NEEDS_REVISION
"""

    print(
        "\nManager evaluating implementation..."
    )

    response = llm.invoke(
        manager_prompt
    )

    decision = extract_text(
        response.content
    ).strip()

    # --------------------------------------------------------
    # Normalize decision
    # --------------------------------------------------------

    if "APPROVED" in decision.upper():

        decision = "APPROVED"

    else:

        decision = "NEEDS_REVISION"

    print(
        "\nManager decision:",
        decision
    )

    # --------------------------------------------------------
    # STATE UPDATE
    # --------------------------------------------------------

    return {
        "decision": decision
    }


# ============================================================
# 10. BUILD LANGGRAPH
# ============================================================

workflow = StateGraph(
    CrewState
)


# ------------------------------------------------------------
# Add nodes
# ------------------------------------------------------------

workflow.add_node(
    "developer",
    developer_node
)

workflow.add_node(
    "tester",
    tester_node
)

workflow.add_node(
    "manager",
    manager_node
)


# ------------------------------------------------------------
# Add edges
# ------------------------------------------------------------

workflow.add_edge(
    START,
    "developer"
)

workflow.add_edge(
    "developer",
    "tester"
)

workflow.add_edge(
    "tester",
    "manager"
)

workflow.add_edge(
    "manager",
    END
)


# ------------------------------------------------------------
# Compile
# ------------------------------------------------------------

crew_graph = workflow.compile()


print("\n")
print("=" * 60)
print("LANGGRAPH COMPILED SUCCESSFULLY")
print("=" * 60)


# ============================================================
# 11. API INPUT MODEL
# ============================================================

class AgentInput(BaseModel):

    input: str = Field(
        description="Coding task for the Developer agent"
    )


# ============================================================
# 12. FORMAT INPUT FOR LANGGRAPH
# ============================================================

def format_for_graph(x) -> dict:

    # LangServe normally sends a dictionary.
    # We also support AgentInput directly.

    if isinstance(x, dict):

        user_input = x.get(
            "input",
            ""
        )

    else:

        user_input = x.input


    if not user_input:

        raise ValueError(
            "Input cannot be empty."
        )


    return {
        "task": user_input
    }


# ============================================================
# 13. EXTRACT FINAL GRAPH RESPONSE
# ============================================================

def extract_graph_response(
    graph_output
) -> str:

    if not isinstance(
        graph_output,
        dict
    ):

        return str(
            graph_output
        )


    # --------------------------------------------------------
    # Extract values from final state
    # --------------------------------------------------------

    task = graph_output.get(
        "task",
        ""
    )

    code = graph_output.get(
        "code",
        ""
    )

    test_cases = graph_output.get(
        "test_cases",
        ""
    )

    execution_output = graph_output.get(
        "execution_output",
        ""
    )

    report = graph_output.get(
        "report",
        ""
    )

    decision = graph_output.get(
        "decision",
        ""
    )


    # --------------------------------------------------------
    # Return JSON string
    # --------------------------------------------------------

    result = {

        "task": task,

        "developer": {
            "code": code
        },

        "tester": {
            "test_cases": test_cases,
            "execution_output": execution_output,
            "report": report
        },

        "manager": {
            "decision": decision
        }
    }


    return json.dumps(
        result,
        indent=2
    )


# ============================================================
# 14. CREATE LANGSERVE CHAIN
# ============================================================

formatted_crew_chain = (

    RunnableLambda(
        format_for_graph
    )

    | crew_graph

    | RunnableLambda(
        extract_graph_response
    )

).with_types(
    input_type=AgentInput,
    output_type=str
)


# ============================================================
# 15. FASTAPI APP
# ============================================================

app = FastAPI(

    title="AI Developer Tester Manager",

    version="1.0",

    description=(
        "A LangGraph workflow using Gemini with "
        "Developer, Tester, and Manager nodes. "
        "Served through FastAPI and LangServe."
    )
)


# ============================================================
# 16. ROOT ENDPOINT
# ============================================================

@app.get("/")
def root():

    return {

        "status": "online",

        "service": (
            "AI Developer Tester Manager"
        ),

        "model": (
            "gemini-3.1-flash-lite-preview"
        ),

        "message": (
            "Server is running. "
            "Visit /crew/playground/ to test the workflow."
        )
    }


# ============================================================
# 17. HEALTH ENDPOINT
# ============================================================

@app.get("/health")
def health():

    return {
        "status": "healthy"
    }


# ============================================================
# 18. LANGSERVE ROUTE
# ============================================================

add_routes(

    app,

    formatted_crew_chain,

    path="/crew"
)


# ============================================================
# 19. START SERVER
# ============================================================

if __name__ == "__main__":

    port = int(
        os.environ.get(
            "PORT",
            8000
        )
    )

    uvicorn.run(

        app,

        host="0.0.0.0",

        port=port
    )
