import os
import sys
import io
import traceback
from typing import TypedDict, List, Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from langchain_core.messages import BaseMessage, HumanMessage
from langchain_core.tools import tool
from langgraph.graph import StateGraph, START, END
from langchain_google_genai import ChatGoogleGenerativeAI


# ============================================================
# 1. GEMINI / LLM INITIALIZATION
# ============================================================

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise RuntimeError(
        "GEMINI_API_KEY environment variable is not set."
    )


llm_flash = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite-preview",
    google_api_key=api_key
)

llm = llm_flash


# ============================================================
# 2. FASTAPI APPLICATION
# ============================================================

app = FastAPI(
    title="Agentic AI Developer Tester",
    description="LLM-powered Developer → Tester → Manager workflow",
    version="1.0.0"
)


# ============================================================
# 3. REQUEST MODEL
# ============================================================

class TaskRequest(BaseModel):
    task: str


# ============================================================
# 4. LANGGRAPH STATE
# ============================================================

class CrewState(TypedDict, total=False):

    # Original user task
    task: Optional[str]

    # Message history
    messages: List[BaseMessage]

    # Code generated by Developer
    code: Optional[str]

    # Test report generated by Tester
    report: Optional[str]

    # Graph routing
    next_step: Optional[str]


# ============================================================
# 5. TOOLS
# ============================================================

@tool
def run_python_code(code: str) -> str:
    """
    Execute Python code and return stdout or an error traceback.

    NOTE:
    This uses exec() and therefore should NOT be considered
    a secure sandbox for arbitrary/untrusted code.
    """

    if not isinstance(code, str):
        code = str(code)

    # Remove accidental Markdown code fences
    clean_code = (
        code
        .replace("```python", "")
        .replace("```", "")
        .strip()
    )

    old_stdout = sys.stdout
    new_stdout = io.StringIO()

    sys.stdout = new_stdout

    try:

        local_scope = {}

        exec(
            clean_code,
            {},
            local_scope
        )

        result = new_stdout.getvalue()

    except Exception:

        result = (
            "Execution Error:\n"
            + traceback.format_exc()
        )

    finally:

        sys.stdout = old_stdout

    if result.strip():
        return result.strip()

    return "Success (no terminal output)"


@tool
def generate_test_cases(task_description: str) -> str:
    """
    Generate 3 to 5 specific test scenarios for a coding task.
    """

    prompt = (
        "You are a Senior QA Engineer.\n\n"
        "Generate 3 to 5 highly specific test scenarios "
        "for the following coding task:\n\n"
        f"{task_description}\n\n"
        "Requirements:\n"
        "- Include standard cases.\n"
        "- Include edge cases.\n"
        "- Be specific about inputs and expected behavior.\n"
        "- Return the scenarios as a numbered list.\n"
    )

    response = llm.invoke(prompt)

    content = response.content

    if isinstance(content, list):

        if not content:
            return "No test cases generated."

        first_item = content[0]

        if isinstance(first_item, dict):
            return str(
                first_item.get(
                    "text",
                    "No test cases generated."
                )
            )

        return str(first_item)

    return str(content)


# ============================================================
# 6. DEVELOPER NODE
# ============================================================

def real_time_developer(state: CrewState):

    print("[Developer] Generating code...")

    # Get task from shared state
    task = state.get("task")

    if not task:
        raise ValueError(
            "Developer could not find 'task' in state."
        )

    developer_prompt = (
        "You are a Senior Python Developer.\n\n"
        "Solve the following coding task:\n\n"
        f"{task}\n\n"
        "Instructions:\n"
        "1. Write clean Python code.\n"
        "2. Return ONLY Python code.\n"
        "3. Do not use Markdown.\n"
        "4. Do not include ```python fences.\n"
        "5. Make the code executable.\n"
    )

    response = llm_flash.invoke(
        developer_prompt
    )

    content = response.content

    # --------------------------------------------------------
    # Safely extract Gemini content
    # --------------------------------------------------------

    if isinstance(content, list):

        if not content:
            code_str = ""

        elif isinstance(content[0], dict):

            code_str = content[0].get(
                "text",
                ""
            )

        else:

            code_str = str(content[0])

    else:

        code_str = str(content)

    # Remove accidental Markdown fences
    code_str = (
        code_str
        .replace("```python", "")
        .replace("```", "")
        .strip()
    )

    if not code_str:

        raise ValueError(
            "Developer returned empty code."
        )

    print("[Developer] Code generated successfully.")

    # IMPORTANT:
    #
    # We only update `code` and `next_step`.
    #
    # Existing state:
    #   task
    #   messages
    #
    # is preserved by LangGraph.

    return {
        "code": code_str,
        "next_step": "tester"
    }


# ============================================================
# 7. TESTER NODE
# ============================================================

def real_time_tester(state: CrewState):

    print("[Tester] Testing generated code...")

    # Get task from shared state
    task = state.get("task")

    # Get Developer's code from shared state
    code = state.get("code")

    if not task:
        raise ValueError(
            "Tester could not find 'task' in state."
        )

    if not code:
        raise ValueError(
            "Tester could not find 'code' in state."
        )

    # --------------------------------------------------------
    # Generate test scenarios
    # --------------------------------------------------------

    print("[Tester] Generating test scenarios...")

    test_cases = generate_test_cases.invoke(
        task
    )

    if isinstance(test_cases, list):

        if not test_cases:

            cases_str = "No test cases generated."

        elif isinstance(test_cases[0], dict):

            cases_str = test_cases[0].get(
                "text",
                "No test cases generated."
            )

        else:

            cases_str = str(test_cases[0])

    else:

        cases_str = str(test_cases)

    # --------------------------------------------------------
    # Execute Developer code
    # --------------------------------------------------------

    print("[Tester] Executing generated code...")

    execution_result = run_python_code.invoke(
        {
            "code": code
        }
    )

    # --------------------------------------------------------
    # Create report
    # --------------------------------------------------------

    report = (
        "### EXECUTION OUTPUT\n\n"
        f"{execution_result}\n\n"
        "### GENERATED TEST SCENARIOS\n\n"
        f"{cases_str}"
    )

    print("[Tester] Test report generated.")

    # IMPORTANT:
    #
    # Existing state:
    #   task
    #   messages
    #   code
    #
    # is preserved.
    #
    # We add:
    #   report

    return {
        "report": report,
        "next_step": "manager"
    }


# ============================================================
# 8. MANAGER NODE
# ============================================================

def manager_decision_node(state: CrewState):

    print("[Manager] Reviewing test report...")

    task = state.get("task")
    code = state.get("code")
    report = state.get("report")

    # For an API workflow, there is no input() here.
    #
    # The Manager's role is represented by the final state.
    #
    # The workflow finishes after the report is generated.

    manager_report = (
        "### MANAGER REVIEW\n\n"
        "Task received and processed successfully.\n\n"
        f"Task:\n{task}\n\n"
        f"Developer Code:\n{code}\n\n"
        f"Tester Report:\n{report}"
    )

    return {
        "report": manager_report,
        "next_step": "end"
    }


# ============================================================
# 9. GRAPH CONSTRUCTION
# ============================================================

workflow = StateGraph(CrewState)


# ------------------------------------------------------------
# Register nodes
# ------------------------------------------------------------

workflow.add_node(
    "developer",
    real_time_developer
)

workflow.add_node(
    "tester",
    real_time_tester
)

workflow.add_node(
    "manager",
    manager_decision_node
)


# ============================================================
# GRAPH EDGES
# ============================================================

# START → Developer
workflow.add_edge(
    START,
    "developer"
)

# Developer → Tester
workflow.add_edge(
    "developer",
    "tester"
)

# Tester → Manager
workflow.add_edge(
    "tester",
    "manager"
)


# ============================================================
# MANAGER → END
# ============================================================

def route_from_manager(state: CrewState):

    if state.get("next_step") == "end":
        return END

    return END


workflow.add_conditional_edges(
    "manager",
    route_from_manager
)


# ============================================================
# COMPILE GRAPH
# ============================================================

rt_app = workflow.compile()

print("LangGraph workflow compiled successfully.")


# ============================================================
# 10. ROOT ENDPOINT
# ============================================================

@app.get("/")
def root():

    return {
        "status": "online",
        "service": "Agentic AI Developer Tester",
        "version": "1.0.0"
    }


# ============================================================
# 11. HEALTH CHECK
# ============================================================

@app.get("/health")
def health():

    return {
        "status": "healthy"
    }


# ============================================================
# 12. RUN AGENTIC WORKFLOW
# ============================================================

@app.post("/run")
def run_task(request: TaskRequest):

    if not request.task.strip():

        raise HTTPException(
            status_code=400,
            detail="Task cannot be empty."
        )

    print("\n" + "=" * 60)
    print("NEW TASK")
    print("=" * 60)

    print(request.task)

    # --------------------------------------------------------
    # Initial LangGraph state
    # --------------------------------------------------------

    initial_state: CrewState = {

        "task": request.task,

        "messages": [
            HumanMessage(
                content=request.task
            )
        ],

        "code": None,

        "report": None,

        "next_step": "developer"
    }

    try:

        # ----------------------------------------------------
        # Run LangGraph
        # ----------------------------------------------------

        result = rt_app.invoke(
            initial_state,
            config={
                "recursion_limit": 20
            }
        )

        # ----------------------------------------------------
        # Return final state
        # ----------------------------------------------------

        return {
            "success": True,
            "task": result.get("task"),
            "code": result.get("code"),
            "report": result.get("report"),
            "next_step": result.get("next_step")
        }

    except Exception as e:

        print(
            "Workflow execution failed:"
        )

        traceback.print_exc()

        raise HTTPException(
            status_code=500,
            detail=str(e)
        )


# ============================================================
# 13. LOCAL DEVELOPMENT
# ============================================================

if __name__ == "__main__":

    import uvicorn

    uvicorn.run(
        "app:app",
        host="0.0.0.0",
        port=int(
            os.getenv(
                "PORT",
                "8000"
            )
        ),
        reload=False
    )
