# ============================================================
# INSTALLATION
# ============================================================

# Run this cell once in Google Colab if needed:
#
# !pip install -U langgraph langchain langchain-core langchain-google-genai


# ============================================================
# IMPORTS
# ============================================================

import sys
import io
import traceback

from typing import TypedDict, List, Optional, Annotated

from langchain_core.messages import BaseMessage, HumanMessage
from langchain_core.tools import tool

from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages

from langchain_google_genai import ChatGoogleGenerativeAI

from google.colab import userdata


# ============================================================
# 1. GEMINI API INITIALIZATION
# ============================================================

print("=" * 60)
print("INITIALIZING GEMINI")
print("=" * 60)

try:
    api_key = userdata.get("GEMINI_API_KEY")

    if not api_key:
        raise ValueError("GEMINI_API_KEY is empty.")

    print("API Key loaded successfully.")

except Exception as e:
    print("ERROR: Could not load GEMINI_API_KEY.")
    print(e)
    raise


# ------------------------------------------------------------
# Create Gemini LLM
# ------------------------------------------------------------

llm_flash = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite-preview",
    google_api_key=api_key,
    temperature=0
)

llm = llm_flash

print("Gemini LLM initialized successfully.")


# ============================================================
# 2. STATE DEFINITION
# ============================================================

class CrewState(TypedDict, total=False):

    # Messages are accumulated using add_messages.
    messages: Annotated[List[BaseMessage], add_messages]

    # Current workflow routing decision.
    next_step: Optional[str]

    # Code generated by Developer.
    code: Optional[str]

    # Test report generated by Tester.
    report: Optional[str]


# ============================================================
# 3. HELPER FUNCTION
# ============================================================

def extract_text(content) -> str:
    """
    Safely convert Gemini/LangChain response content
    into a normal string.
    """

    if content is None:
        return ""

    if isinstance(content, str):
        return content

    if isinstance(content, list):

        parts = []

        for item in content:

            if isinstance(item, dict):

                if "text" in item:
                    parts.append(str(item["text"]))

            else:
                parts.append(str(item))

        return "".join(parts)

    return str(content)


# ============================================================
# 4. PYTHON EXECUTION TOOL
# ============================================================

@tool
def run_python_code(code: str) -> str:
    """
    Execute Python code and return standard output
    or the error traceback.
    """

    if not isinstance(code, str):
        code = str(code)

    # Remove markdown code fences if Gemini accidentally returns them.
    clean_code = (
        code
        .replace("```python", "")
        .replace("```", "")
        .strip()
    )

    old_stdout = sys.stdout
    new_stdout = io.StringIO()

    sys.stdout = new_stdout

    try:

        # Separate namespace for execution.
        local_scope = {}

        exec(clean_code, {}, local_scope)

        result = new_stdout.getvalue()

    except Exception:

        result = (
            "Execution Error:\n"
            + traceback.format_exc()
        )

    finally:

        sys.stdout = old_stdout

    result = result.strip()

    if result:
        return result

    return "Success (no terminal output)"


# ============================================================
# 5. TEST CASE GENERATION TOOL
# ============================================================

@tool
def generate_test_cases(task_description: str) -> str:
    """
    Generate specific test scenarios for a coding task.
    """

    prompt = f"""
You are a Senior QA Engineer.

Generate 3 to 5 highly specific test scenarios
for the following Python coding task:

{task_description}

Requirements:

1. Include normal/standard cases.
2. Include edge cases.
3. Include invalid input cases where appropriate.
4. Explain what each test should verify.
5. Return only a numbered list.
"""

    response = llm.invoke(prompt)

    return extract_text(response.content)


# ============================================================
# 6. DEBUG STATE FUNCTION
# ============================================================

def print_state(label: str, state: CrewState):

    print("\n")
    print("=" * 70)
    print(f"STATE DEBUG -> {label}")
    print("=" * 70)

    print("\nNEXT STEP:")
    print(state.get("next_step"))

    print("\nCODE:")
    code = state.get("code")

    if code:
        print(code)
    else:
        print("<NO CODE>")

    print("\nREPORT:")
    report = state.get("report")

    if report:
        print(report)
    else:
        print("<NO REPORT>")

    print("\nMESSAGES:")

    messages = state.get("messages", [])

    if not messages:
        print("<NO MESSAGES>")
    else:

        for i, message in enumerate(messages):

            print(f"\nMessage {i + 1}")
            print(f"Type: {type(message).__name__}")
            print(f"Content: {message.content}")

    print("=" * 70)


# ============================================================
# 7. TASK INPUT NODE
# ============================================================

def task_input_node(state: CrewState):

    print("\n")
    print("=" * 70)
    print("NEW TASK INITIALIZATION")
    print("=" * 70)

    user_task = input(
        "\nEnter the coding task "
        "(or type 'exit' to quit): "
    ).strip()

    # --------------------------------------------------------
    # EXIT
    # --------------------------------------------------------

    if user_task.lower() == "exit":

        print("\nExiting workflow...")

        return {
            "next_step": "exit"
        }

    # --------------------------------------------------------
    # Create user message
    # --------------------------------------------------------

    message = HumanMessage(
        content=user_task
    )

    new_state = {
        "messages": [message],
        "next_step": "developer",

        # Clear old task information.
        "code": None,
        "report": None
    }

    print_state("AFTER TASK INPUT", new_state)

    return new_state


# ============================================================
# 8. DEVELOPER NODE
# ============================================================

def real_time_developer(state: CrewState):

    print("\n")
    print("=" * 70)
    print("DEVELOPER NODE")
    print("=" * 70)

    # --------------------------------------------------------
    # Check messages
    # --------------------------------------------------------

    messages = state.get("messages", [])

    if not messages:

        raise ValueError(
            "Developer received no messages."
        )

    # --------------------------------------------------------
    # Get latest user task
    # --------------------------------------------------------

    task = messages[-1].content

    print("\nDeveloper received task:")
    print(task)

    # --------------------------------------------------------
    # Prompt Gemini
    # --------------------------------------------------------

    dev_prompt = f"""
You are a Senior Python Developer.

Solve the following coding task:

{task}

Requirements:

1. Write clean Python code.
2. Make the program executable.
3. Handle reasonable edge cases.
4. Do not explain the solution.
5. Do not use Markdown.
6. Return ONLY the Python source code.
"""

    print("\nCalling Gemini Developer...")

    response = llm_flash.invoke(dev_prompt)

    # --------------------------------------------------------
    # Extract response
    # --------------------------------------------------------

    code_str = extract_text(response.content)

    # --------------------------------------------------------
    # Clean Markdown fences
    # --------------------------------------------------------

    code_str = (
        code_str
        .replace("```python", "")
        .replace("```Python", "")
        .replace("```", "")
        .strip()
    )

    if not code_str:

        raise ValueError(
            "Developer generated empty code."
        )

    # --------------------------------------------------------
    # Create updated state
    # --------------------------------------------------------

    updated_state = {
        "code": code_str
    }

    print("\nDeveloper generated:")
    print("-" * 70)
    print(code_str)
    print("-" * 70)

    # --------------------------------------------------------
    # IMPORTANT:
    # The returned code becomes part of LangGraph state.
    # --------------------------------------------------------

    print("\nDeveloper -> Tester state update:")

    print("code exists:", bool(code_str))
    print("code length:", len(code_str))

    return updated_state


# ============================================================
# 9. TESTER NODE
# ============================================================

def real_time_tester(state: CrewState):

    print("\n")
    print("=" * 70)
    print("TESTER NODE")
    print("=" * 70)

    # --------------------------------------------------------
    # Check incoming state
    # --------------------------------------------------------

    print("\nTester received state:")

    print("messages:",
          len(state.get("messages", [])))

    print("code exists:",
          bool(state.get("code")))

    print("report exists:",
          bool(state.get("report")))

    # --------------------------------------------------------
    # Get task
    # --------------------------------------------------------

    messages = state.get("messages", [])

    if not messages:

        raise ValueError(
            "Tester received no messages."
        )

    task = messages[-1].content

    # --------------------------------------------------------
    # Get Developer code
    # --------------------------------------------------------

    code = state.get("code")

    if not code:

        raise ValueError(
            "TESTER ERROR: Developer code was not found in state."
        )

    print("\nTester successfully received Developer code.")

    print("-" * 70)
    print(code)
    print("-" * 70)

    # ========================================================
    # Generate test scenarios
    # ========================================================

    print("\nGenerating test scenarios...")

    test_cases = generate_test_cases.invoke(
        task
    )

    cases_str = extract_text(test_cases)

    # ========================================================
    # Execute Developer code
    # ========================================================

    print("\nExecuting Developer code...")

    execution_result = run_python_code.invoke(
        {
            "code": code
        }
    )

    # ========================================================
    # Build report
    # ========================================================

    report = f"""
### EXECUTION OUTPUT

{execution_result}

### TEST SCENARIOS EVALUATED

{cases_str}
"""

    # ========================================================
    # Return report to LangGraph state
    # ========================================================

    updated_state = {
        "report": report
    }

    print("\nTester generated report:")
    print("-" * 70)
    print(report)
    print("-" * 70)

    print("\nTester -> Manager state update:")
    print("report exists:", bool(report))
    print("report length:", len(report))

    return updated_state


# ============================================================
# 10. MANAGER NODE
# ============================================================

def manager_decision_node(state: CrewState):

    print("\n")
    print("=" * 70)
    print("MANAGER DASHBOARD")
    print("=" * 70)

    # --------------------------------------------------------
    # IMPORTANT:
    # Read report directly from state.
    # --------------------------------------------------------

    report = state.get("report")

    if report:

        print("\nTEST REPORT:")
        print("-" * 70)
        print(report)
        print("-" * 70)

    else:

        print(
            "\nERROR: Manager did not receive Tester report."
        )

    # --------------------------------------------------------
    # Display state confirmation
    # --------------------------------------------------------

    print("\nMANAGER STATE CHECK:")
    print(
        "Code available:",
        bool(state.get("code"))
    )

    print(
        "Report available:",
        bool(state.get("report"))
    )

    print(
        "Messages available:",
        len(state.get("messages", []))
    )

    print("=" * 70)

    # --------------------------------------------------------
    # Manager decision
    # --------------------------------------------------------

    user_input = input(
        "\nCommand "
        "(store / another): "
    ).lower().strip()

    if user_input == "store":

        return {
            "next_step": "archiver"
        }

    else:

        return {
            "next_step": "task_input"
        }


# ============================================================
# 11. ARCHIVER NODE
# ============================================================

def archiver_node(state: CrewState):

    print("\n")
    print("=" * 70)
    print("ARCHIVER")
    print("=" * 70)

    print(
        "\nTask stored successfully."
    )

    print(
        "Workflow completed."
    )

    return {
        "next_step": "exit"
    }


# ============================================================
# 12. GRAPH CONSTRUCTION
# ============================================================

print("\n")
print("=" * 70)
print("BUILDING LANGGRAPH WORKFLOW")
print("=" * 70)


rt_workflow = StateGraph(CrewState)


# ------------------------------------------------------------
# Add nodes
# ------------------------------------------------------------

rt_workflow.add_node(
    "task_input",
    task_input_node
)

rt_workflow.add_node(
    "developer",
    real_time_developer
)

rt_workflow.add_node(
    "tester",
    real_time_tester
)

rt_workflow.add_node(
    "manager_decision",
    manager_decision_node
)

rt_workflow.add_node(
    "archiver",
    archiver_node
)


# ============================================================
# 13. START -> TASK INPUT
# ============================================================

rt_workflow.add_edge(
    START,
    "task_input"
)


# ============================================================
# 14. TASK INPUT ROUTING
# ============================================================

def route_from_input(state: CrewState):

    next_step = state.get(
        "next_step"
    )

    print(
        f"\n[Router] Task input -> {next_step}"
    )

    if next_step == "exit":

        return END

    return "developer"


rt_workflow.add_conditional_edges(
    "task_input",
    route_from_input
)


# ============================================================
# 15. DEVELOPER -> TESTER
# ============================================================

rt_workflow.add_edge(
    "developer",
    "tester"
)


# ============================================================
# 16. TESTER -> MANAGER
# ============================================================

rt_workflow.add_edge(
    "tester",
    "manager_decision"
)


# ============================================================
# 17. MANAGER ROUTING
# ============================================================

def route_from_decision(state: CrewState):

    next_step = state.get(
        "next_step"
    )

    print(
        f"\n[Router] Manager -> {next_step}"
    )

    if next_step == "archiver":

        return "archiver"

    return "task_input"


rt_workflow.add_conditional_edges(
    "manager_decision",
    route_from_decision
)


# ============================================================
# 18. ARCHIVER -> END
# ============================================================

rt_workflow.add_edge(
    "archiver",
    END
)


# ============================================================
# 19. COMPILE GRAPH
# ============================================================

rt_app = rt_workflow.compile()


print("\n")
print("=" * 70)
print("WORKFLOW COMPILED SUCCESSFULLY")
print("=" * 70)

print(
    """
FLOW:

START
  |
  v
TASK INPUT
  |
  v
DEVELOPER
  |
  |  code
  v
TESTER
  |
  |  report
  v
MANAGER
  |
  +---- store ----> ARCHIVER ----> END
  |
  +---- another --> TASK INPUT
"""
)


# ============================================================
# 20. EXECUTION
# ============================================================

if __name__ == "__main__":

    print("\n")
    print("=" * 70)
    print("STARTING INTERACTIVE PIPELINE")
    print("=" * 70)

    try:

        initial_state: CrewState = {
            "messages": [],
            "next_step": None,
            "code": None,
            "report": None
        }

        final_state = rt_app.invoke(
            initial_state,
            config={
                "recursion_limit": 50
            }
        )

        print("\n")
        print("=" * 70)
        print("FINAL STATE")
        print("=" * 70)

        print_state(
            "FINAL",
            final_state
        )

    except KeyboardInterrupt:

        print(
            "\n\nWorkflow stopped by user."
        )

    except Exception as e:

        print("\n")
        print("=" * 70)
        print("WORKFLOW ERROR")
        print("=" * 70)

        print(
            f"\nError: {e}"
        )

        print("\nFull traceback:")

        traceback.print_exc()